# appveyor.yml

configuration:
- Release

version: "{build}"

environment:
  matrix:
    - platform: Any CPU
      language: csharp
      image: Visual Studio 2015


# Don't let AppVeyor try to detect tests itself
test: off

build_script:
- CALL Main/Nfm/build.cmd

skip_commits:
  message: /.*\[skip appveyor\].*/
